### PR TITLE
DM-39367: Remove hardcoded skymap names

### PR DESCRIPTION
**Pull request by aboucaud**
Exercice as part of the bootcamp

### CODE REVIEW

**Comment by aboucaud** [comment]
I reverted the last commit and the checks are passing locally @arunkannawadi

**Comment by arunkannawadi** [comment]
Thank you. In a separate commit, please remove line 39 in `skyPlot.py` since we don't normally want to have commented out code in `main`.  I think that'd be well within the purview of this ticket.

Would you like to wait till you obtain push access so you can complete the rest of the workflow yourself and get the whole experience?

**Comment by arunkannawadi** [comment]
You'll also need to `drop` the commits instead of reverting them. Happy to walk through the process during the coworking session later.

**Comment by aboucaud** [comment]
> Thank you. In a separate commit, please remove line 39 in `skyPlot.py` since we don't normally want to have commented out code in `main`. I think that'd be well within the purview of this ticket.

Will do

> Would you like to wait till you obtain push access so you can complete the rest of the workflow yourself and get the whole experience?

I sure can

> You'll also need to `drop` the commits instead of reverting them. Happy to walk through the process during the coworking session later.

I am not sure I understand the point behind dropping commits vs reverting them.
Maybe it is related to the fact I am used to squash commits of a PR instead of creating a merge commit, unless there is a reason to do so.
Could you elaborate ?

**Comment by timj** [comment]
You are working on a branch where you have a commit and then the reversion of the commit. The history of this branch does not need to know that you first tried something and then decided against it and so it is better to remove those two commits from the history completely as if they never happened. You can do this with `git rebase -i main` and annotate them with "d" for "drop". If you were reverting something that has already merged to main then that is a different debate.

**Comment by timj** [comment]
> I'll rebase then

Are you aware of the developer guide with detailed instructions on process including a discussion on rebasing? We always need a merge commit and we always require a rebase.

https://developer.lsst.io/work/flow.html

**Comment by timj** [comment]
@arunkannawadi note that you can't run jenkins with a branch on a fork so you will likely need to create a new branch/PR before you can run jenkins and if @aboucaud is going to continue to make PRs they will need to be given push access to this repo.

**Comment by aboucaud** [comment]
Thank you @timj for the pointer. I am still catching up on this. 

I have requested push access to https://github.com/lsst. 
Once I do, I'll publish the branch on this repo and edit the PR accordingly. 

Otherwise we can also drop this PR and let someone else do the same exercice.

**Comment by arunkannawadi** [comment]
I don't expect this specific PR to merge as it is, since I am hoping once @aboucaud gets his accounts, he can cherry-pick the ready-to-merge commits to a proper ticket branch, run Jenkins and then merge. I'm marking this PR as draft for that reason.

**Comment by aboucaud** [comment]
Superseeded by #122

**Pull request closed without merging**
